 trigger:
  branches:
    include:
      - main
  paths:
    include:
      - docusaurus

variables:
  - group: github-credentials # Reference the variable group containing GH_TOKEN, GH_NAME, GH_EMAIL

pr:
  branches:
    include:
      - main
  paths:
    include:
      - docusaurus     

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    persistCredentials: true

  - task: UseNode@1
    inputs:
      version: '22.x'
    displayName: Install Node.js

- script: |
      git config --global user.name "$(GH_NAME)"
      git config --global user.email "$(GH_EMAIL)"
      # Configure Git to use the PAT for authentication
      git config --global credential.helper 'store --file=.git-credentials'
      echo "https://$(GH_NAME):$(GH_TOKEN)@github.com" > .git-credentials
      npm install
      npm run build
      GIT_USER="$(GH_NAME)" yarn deploy
    env:
      GH_NAME: $(GH_NAME)
      GH_EMAIL: $(GH_EMAIL)
      GH_TOKEN: $(GH_TOKEN)
    displayName: 'Install, Build, and Deploy'

  - script: |
      rm -f .git-credentials
    condition: always()
    displayName: 'Clean up credentials file'
