trigger:
  branches:
    include:
      - main
  paths:
    include:
      - docusaurus

pr:
  branches:
    include:
      - main
  paths:
    include:
      - docusaurus     

pool:
  vmImage: ubuntu-latest

variables:
  - group: github-credential-sharethrift

steps:
  - checkout: self
    persistCredentials: true

  - task: UseNode@1
    inputs:
      version: '22.x'
    displayName: 'Install Node.js'

  - script: |
      echo "npm_config_cache is: $(npm_config_cache)"
      npm config list
    displayName: 'Debug npm_config_cache'
    
  - task: Cache@2
    displayName: 'NPM: Restore Cache'
    inputs:
      key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/docusaurus/package-lock.json'
      restoreKeys: |
          npm | "$(Agent.OS)"
      path: 
        $(npm_config_cache)
        $(Build.SourcesDirectory)/docusaurus/node_modules



  - task: Bash@3
    displayName: 'Install, Build, and Deploy'
    inputs:
      targetType: 'inline'
      script: |
        # Debug variable availability
        echo "GH_NAME: $(GH_NAME)"
        echo "GH_EMAIL: $(GH_EMAIL)"
        echo "GH_TOKEN length: ${#GH_TOKEN}"
        echo "Current directory: $(pwd)"
        echo "Git remote URL:"
        git remote -v

        if [ -z "$(GH_TOKEN)" ]; then
          echo "Error: GH_TOKEN is empty or not loaded. Please check the variable group configuration."
          exit 1
        fi

        git config --global user.name "$(GH_NAME)"
        git config --global user.email "$(GH_EMAIL)"
        cd docusaurus
        npm ci



        export GIT_USER=$(GH_NAME)
        export GIT_PASS=$(GH_TOKEN)
        

        npm run deploy --skip-build

