trigger:
  branches:
    include:
      - main
  paths:
    include:
      - docusaurus

pr:
  branches:
    include:
      - main
  paths:
    include:
      - docusaurus     

resources:
  repositories:
    - repository: self
      type: git
      name: simnova/sharethrift
      ref: refs/heads/main
      endpoint: 'Simnova (1)'

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    persistCredentials: true

  # Cache NPM packages to speed up build process.
  - task: Cache@2
    displayName: 'NPM: Restore Cache'
    inputs:
      key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/package-lock.json'
      restoreKeys: |
          npm | "$(Agent.OS)"
      path: $(npm_config_cache)

  - task: UseNode@1
    inputs:
      version: '22.x'
    displayName: Install Node.js

  - task: Bash@3
    displayName: 'Install, Build, and Deploy'
    inputs:
      targetType: 'inline'
      script: |
        # Configure Git with credentials
        git config --global user.name "azure-pipelines"
        git config --global user.email "azure-pipelines@microsoft.com"
        echo "GitHub Token: $GITHUB_TOKEN"
        
        cd docusaurus
        npm ci
        npm run build
        npm run deploy
    env:
      GIT_USER: "azure-pipelines"
      GITHUB_TOKEN: $(System.AccessToken)