trigger:
  branches:
    include:
      - main
  paths:
    include:
      - docusaurus

pr:
  branches:
    include:
      - main
  paths:
    include:
      - docusaurus     

pool:
  vmImage: ubuntu-latest

variables:
  - group: github-credential-sharethrift

steps:
  - checkout: self
    persistCredentials: true

  - task: Cache@2
    displayName: 'NPM: Restore Cache'
    inputs:
      key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/package-lock.json'
      restoreKeys: |
          npm | "$(Agent.OS)"
      path: $(npm_config_cache)

  - task: UseNode@1
    inputs:
      version: '22.x'
    displayName: 'Install Node.js'

  - task: Bash@3
    displayName: 'Install, Build, and Deploy'
    inputs:
      targetType: 'inline'
      script: |
        # Debug variable availability
        echo "GH_NAME: $(GH_NAME)"
        echo "GH_EMAIL: $(GH_EMAIL)"
        echo "GH_TOKEN: $(GH_TOKEN)"
        echo "Token length: ${#GH_TOKEN}"

        if [ -z "$(GH_TOKEN)" ]; then
          echo "Error: GH_TOKEN is empty or not loaded. Please check the variable group configuration."
          exit 1
        fi

        # Set the remote URL with GH_TOKEN as the username
        git remote set-url origin https://heruwala:$(GH_TOKEN)@github.com/simnova/sharethrift.git

        # Configure Git with credentials from variable group
        git config --global user.name "x-access-token"
        # "$(GH_NAME)"
        git config --global user.email "$(GH_EMAIL)"
        git checkout -b main
        
  
        
        # Configure Git to avoid password prompts
        #git config --global http.extraheader "Authorization: token $(GH_TOKEN)"

        echo "machine github.com login heruwala password $(GH_TOKEN)" > ~/.netrc
        cat ~/.netrc
        
        # Verify Git configuration
        echo "Git remote URL:"
        git remote get-url origin
        echo "Using token: $(GH_TOKEN)"

        cd docusaurus
        npm ci
        #npm run build
        echo "Build Complete"
        
        # Deploy using Docusaurus with GIT_USER
        GIT_USER="x-access-token" npm run deploy