 trigger:
  branches:
    include:
      - main
  paths:
    include:
      - docusaurus

variables:
  - group: github-credentials-sharethrift # Reference the variable group containing GH_TOKEN, GH_NAME, GH_EMAIL

pr:
  branches:
    include:
      - main
  paths:
    include:
      - docusaurus     

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    persistCredentials: true

  - task: UseNode@1
    inputs:
      version: '22.x'
    displayName: Install Node.js

- script: |
git config --global user.name "Azure Pipelines"
      git config --global user.email "azure-pipelines@example.com"
      cd docusaurus
      npm install
      npm run build
      npm run deploy
    env:
      GH_NAME: $(GH_NAME)
      GH_EMAIL: $(GH_EMAIL)
      GH_TOKEN: $(GH_TOKEN)
    displayName: 'Install, Build, and Deploy'
