trigger:
  branches:
    include:
      - main
  paths:
    include:
      - docusaurus

pr:
  branches:
    include:
      - main
  paths:
    include:
      - docusaurus     

resources:
  repositories:
    - repository: simnovaRepo
      type: github
      name: simnova/sharethrift
      ref: pg-fix-docusaurus
      endpoint: 'Simnova'

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: simnovaRepo
    persistCredentials: true

  - task: Cache@2
    displayName: 'NPM: Restore Cache'
    inputs:
      key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/package-lock.json'
      restoreKeys: |
          npm | "$(Agent.OS)"
      path: $(npm_config_cache)

  - task: UseNode@1
    inputs:
      version: '22.x'
    displayName: 'Install Node.js'

  - task: Bash@3
    displayName: 'Install, Build, and Deploy'
    inputs:
      targetType: 'inline'
      script: |
        # Configure Git with credentials
        git config --global user.name "${GIT_USER}"
        git config --global user.email "${GIT_USER_EMAIL}"
        
        # Set the remote URL with token
        git remote set-url origin https://x-access-token:${GIT_PASS}@github.com/simnova/sharethrift.git
        
        # Verify Git configuration
        echo "Git remote URL:"
        git remote get-url origin

        cd docusaurus
        npm ci
        npm run build
        echo "Build Complete"
        
        # Deploy using Docusaurus
        npm run deploy
    env:
      GIT_USER: "azure-pipelines"
      GIT_USER_EMAIL: "azure-pipelines@microsoft.com"
      GIT_PASS: $(System.AccessToken)