trigger:
  branches:
    include:
      - main
  paths:
    include:
      - docusaurus

pr:
  branches:
    include:
      - main
  paths:
    include:
      - docusaurus     

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    persistCredentials: true

  # Cache NPM packages to speed up build process.
  - task: Cache@2
    displayName: 'NPM: Restore Cache'
    inputs:
      key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/package-lock.json'
      restoreKeys: |
          npm | "$(Agent.OS)"
      path: $(npm_config_cache)

  - task: UseNode@1
    inputs:
      version: '22.x'
    displayName: Install Node.js

  - task: Bash@3
    displayName: 'Install, Build, and Deploy'
    inputs:
      targetType: 'inline'
      script: |
        # Configure Git with credentials
        git config --global user.name "Azure Pipelines"
        git config --global user.email "azure-pipelines@microsoft.com"
        
        # Configure GitHub authentication using credential helper
        git config --global credential.helper store
        echo "https://nobody:${GITHUB_TOKEN}@github.com" > ~/.git-credentials
        chmod 600 ~/.git-credentials
        
        cd docusaurus
        npm ci
        npm run build
        npm run deploy
    env:
      GIT_USER: "Azure Pipelines"
      GITHUB_TOKEN: $(System.AccessToken)