trigger:
  branches:
    include:
      - main
  paths:
    include:
      - docusaurus

pr:
  branches:
    include:
      - main
  paths:
    include:
      - docusaurus     

resources:
  repositories:
    - repository: self
      type: git
      name: simnova/sharethrift
      ref: refs/heads/main
      endpoint: 'Simnova (1)'

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    persistCredentials: true

  # Cache NPM packages to speed up build process.
  - task: Cache@2
    displayName: 'NPM: Restore Cache'
    inputs:
      key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/package-lock.json'
      restoreKeys: |
          npm | "$(Agent.OS)"
      path: $(npm_config_cache)

  - task: UseNode@1
    inputs:
      version: '22.x'
    displayName: Install Node.js

  - task: Bash@3
    displayName: 'Install, Build, and Deploy'
    inputs:
      targetType: 'inline'
      script: |
        # Configure Git with credentials
        git config --global user.name "${GIT_USER}"
        git config --global user.email "${GIT_EMAIL}"
        echo "Git User: $GIT_USER"
        echo "Git Email: $GIT_EMAIL"

        # Configure Git credentials using URL-specific configuration
        git config --global credential.helper '!f() { echo "username=x-access-token"; echo "password=${GITHUB_TOKEN}"; }; f'
        
        # Set the remote URL with token
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/simnova/sharethrift.git
        
        # Verify Git configuration
        echo "Git remote URL:"
        git remote get-url origin

        echo "System Access Token env: ${GITHUB_TOKEN}"
        echo "System Access Token build variable: $(System.AccessToken)"

        cd docusaurus
        npm ci
        npm run build
        
        # Configure Git in the docusaurus directory as well
        git config user.name "${GIT_USER}"
        git config user.email "${GIT_EMAIL}"
        git config credential.helper '!f() { echo "username=x-access-token"; echo "password=${GITHUB_TOKEN}"; }; f'
        
        # Deploy using Docusaurus with explicit environment variables
        GITHUB_TOKEN="${GITHUB_TOKEN}" GIT_USER="${GIT_USER}" USE_SSH=false npm run deploy
    env:
      GIT_USER: "azure-pipelines"
      GIT_EMAIL: "azure-pipelines@microsoft.com"
      GITHUB_TOKEN: $(System.AccessToken)