trigger:
  branches:
    include:
      - main
  paths:
    include:
      - docusaurus

pr:
  branches:
    include:
      - main
  paths:
    include:
      - docusaurus     

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    persistCredentials: true

  # Cache NPM packages to speed up build process.
  - task: Cache@2
    displayName: 'NPM: Restore Cache'
    inputs:
      key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/package-lock.json'
      restoreKeys: |
          npm | "$(Agent.OS)"
      path: $(npm_config_cache)

  - task: UseNode@1
    inputs:
      version: '22.x'
    displayName: Install Node.js

  - script: |
      cd docusaurus
      npm ci
      npm run build
      npm run deploy
    env:
      GIT_USER: "git"
      GH_TOKEN: $(System.AccessToken)
    displayName: 'Install, Build, and Deploy'
