 trigger:
  branches:
    include:
      - main
  paths:
    include:
      - docusaurus

variables:
  - group: github-credentials-sharethrift # Reference the variable group containing GH_TOKEN, GH_NAME, GH_EMAIL

pr:
  branches:
    include:
      - main
  paths:
    include:
      - docusaurus     

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    persistCredentials: true

  - task: UseNode@1
    inputs:
      version: '22.x'
    displayName: Install Node.js

- script: |
      git config --global user.name "$(GH_NAME)"
      git config --global user.email "$(GH_EMAIL)"
      # Configure Git to use credential cache
      git config --global credential.helper 'cache --timeout=300'
      # Provide credentials to the cache
      echo "protocol=https" | git credential approve
      echo "host=github.com" | git credential approve
      echo "username=$(GH_NAME)" | git credential approve
      echo "password=$(GH_TOKEN)" | git credential approve
      npm install
      npm run build
      GIT_USER="$(GH_NAME)" yarn deploy
    env:
      GH_NAME: $(GH_NAME)
      GH_EMAIL: $(GH_EMAIL)
      GH_TOKEN: $(GH_TOKEN)
    displayName: 'Install, Build, and Deploy'
