trigger:
  branches:
    include:
      - main
  paths:
    include:
      - docusaurus

pr:
  branches:
    include:
      - main
  paths:
    include:
      - docusaurus     

pool:
  vmImage: ubuntu-latest

variables:
  - group: github-credential-sharethrift

steps:
  - checkout: self
    persistCredentials: true

  - task: Cache@2
    displayName: 'NPM: Restore Cache'
    inputs:
      key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/package-lock.json'
      restoreKeys: |
          npm | "$(Agent.OS)"
      path: $(npm_config_cache)

  - task: UseNode@1
    inputs:
      version: '22.x'
    displayName: 'Install Node.js'

  - task: Bash@3
    displayName: 'Install, Build, and Deploy'
    inputs:
      targetType: 'inline'
      script: |
        # Debug variable availability
        echo "GH_NAME: ${GH_NAME}"
        echo "GH_EMAIL: ${GH_EMAIL}"
        echo "GH_TOKEN: ${GH_TOKEN}"
        echo "Token length: ${#GH_TOKEN}"

        # Set the remote URL with a placeholder username and token as password
        git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/simnova/sharethrift.git
        
        # Configure Git to use token authentication without prompts
        git config --global http.extraheader "Authorization: token ${GH_TOKEN}"
        
        # Verify Git configuration
        echo "Git remote URL:"
        git remote get-url origin
        echo "Using token: ${GH_TOKEN}"

        cd docusaurus
        npm ci
        npm run build
        echo "Build Complete"
        
        # Deploy using Docusaurus with GIT_USER
        GIT_USER="x-access-token" npm run deploy