trigger:
 branches:
   include:
     - main

pr:
  branches:
    include:
     - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: sonarcloud-credential-sharethrift
  - group: github-credential-sharethrift
  - group: ui-sharethrift-settings-sharethrift
  - name: deploymentDefaultLocation
    value: 'eastus2'
  - name: ServiceConnectionName
    value: 'ShareThrift-MSDN'
  - name: vmImageName
    value: 'ubuntu-latest'
  - name: system.debug
    value: true
  - name: pnpm_config_cache
    value: $(Pipeline.Workspace)/.pnpm-store
  - name: SONAR_USER_HOME
    value: $(Pipeline.Workspace)/.sonar

stages:
  - template: ./build-pipeline/core/monorepo-build-stage.yml
    parameters:
      vmImageName: $(vmImageName)
      pnpm_config_cache: $(pnpm_config_cache)
      isPnpmCacheAvailable: 'true'
      disableSonarCloudTasks: 'false'
      SONAR_USER_HOME: $(SONAR_USER_HOME)
      SonarCloud: 'sonarcloud'
      SonarCloud_organization: 'simnova'
      SonarCloud_scannerMode: 'CLI'
      SonarCloud_configMode: 'manual'
      SonarCloud_cliProjectKey: 'simnova_sharethrift-data-access'
      SonarCloud_cliProjectName: 'sharethrift-data-access'
      buildEnvSettings:
        VITE_AAD_B2C_ACCOUNT_AUTHORITY: $(VITE_AAD_B2C_ACCOUNT_AUTHORITY_DEV)
        VITE_AAD_B2C_ACCOUNT_CLIENTID: $(VITE_AAD_B2C_ACCOUNT_CLIENTID_DEV)
        VITE_AAD_B2C_REDIRECT_URI: $(VITE_AAD_B2C_REDIRECT_URI_DEV)
        VITE_AAD_B2C_ACCOUNT_SCOPES: $(VITE_AAD_B2C_ACCOUNT_SCOPES_DEV)
        VITE_FUNCTION_ENDPOINT: $(VITE_FUNCTION_ENDPOINT_DEV)


  - template: ./build-pipeline/core/monorepo-deployment-stage.yml
    parameters:
      stageName: 'DEV'
      environmentNameBicep: 'dev'
      environmentNameDevOps: 'sharethrift-dev'
      vmImageName: $(vmImageName)
      ServiceConnectionName: $(ServiceConnectionName)
      deploymentDefaultLocation: $(deploymentDefaultLocation)
      resourceGroupName: 'rg-sharethrift'
      appSettingsJsonFileRelativePathPri: 'apps/api/build-pipelines/config/dev-pri.json'
      frontDoorProfileName: 'simnova-afd'
      frontDoorEndpointName: 'sth-fde-ged3a8gxcvfxafaf'