trigger:
 branches:
   include:
     - main

pr:
  branches:
    include:
     - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: sonarcloud-credential-sharethrift
  - name: deploymentDefaultLocation
    value: 'eastus2'
  - name: ServiceConnectionName
    value: 'ShareThrift-MSDN'
  - name: vmImageName
    value: 'ubuntu-latest'
  - name: system.debug
    value: true
  - name: npm_config_cache
    value: $(Pipeline.Workspace)/.npm
  - name: SONAR_USER_HOME
    value: $(Pipeline.Workspace)/.sonar

stages:
  - template: ./build-pipeline/core/monorepo-build-stage.yml
    parameters:
      vmImageName: $(vmImageName)
      npm_config_cache: $(npm_config_cache)
      isNpmCacheAvailable: 'true'
      disableSonarCloudTasks: 'false'
      SONAR_USER_HOME: $(SONAR_USER_HOME)
      SonarCloud: 'sonarcloud'
      SonarCloud_organization: 'simnova'
      SonarCloud_scannerMode: 'CLI'
      SonarCloud_configMode: 'manual'
      SonarCloud_cliProjectKey: 'simnova_sharethrift-data-access'
      SonarCloud_cliProjectName: 'sharethrift-data-access'

  - template: ./build-pipeline/core/monorepo-deployment-stage.yml
    parameters:
      stageName: 'DEV'
      environmentNameBicep: 'dev'
      environmentNameDevOps: 'sharethrift-dev'
      vmImageName: $(vmImageName)
      ServiceConnectionName: $(ServiceConnectionName)
      deploymentDefaultLocation: $(deploymentDefaultLocation)
      resourceGroupName: 'rg-sharethrift'