# Node.js Function App to Linux on Azure
# Build a Node.js function app and deploy it to Azure as a Linux function app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript


trigger:
 paths:
   include:
     - api
 branches:
   include:
     - main

pr:
  branches:
    include:
      - main
  paths:
    include:
      - api

pool:
  vmImage: ubuntu-latest

variables:
  deploymentDefaultLocation: 'eastus2'
  ServiceConnectionName: 'ShareThrift-MSDN'
  vmImageName: 'ubuntu-latest'
  system.debug: true
  npm_config_cache: $(Pipeline.Workspace)/.npm
  SONAR_USER_HOME: $(Pipeline.Workspace)/.sonar

stages:
  - template: ./build-pipeline/core/function-app-build-stage.yml
    parameters:
      vmImageName: $(vmImageName)
      npm_config_cache: $(npm_config_cache)
      isNpmCacheAvailable: 'true'
      disableSonarCloudTasks: 'false'
      SONAR_USER_HOME: $(SONAR_USER_HOME)
      SonarCloud: 'sonarcloud'
      SonarCloud_organization: 'simnova'
      SonarCloud_scannerMode: 'CLI'
      SonarCloud_configMode: 'manual'
      SonarCloud_cliProjectKey: 'simnova_cellix-data-access'
      SonarCloud_cliProjectName: 'cellix-data-access'

  - template: ./build-pipeline/core/function-app-deployment-stage.yml
    parameters: 
      stageName: 'DEV'
      #dependsOnStage: Core
      # environmentNameBicep: 'dev'
      environmentNameDevOps: 'cellix-dev'
      vmImageName: $(vmImageName)
      ServiceConnectionName: $(ServiceConnectionName)
      deploymentDefaultLocation: $(deploymentDefaultLocation)
      resourceGroupName: 'rg-sharethrift'
      functionAppNamePri: 'Cellix-func-app'
      #functionAppNameSec: 'ahp-dev-func-sec-$(UniqueStringDev)'
      appSettingsJsonFileRelativePathPri: '/build-pipeline/config/dev-pri.json'
      #appSettingsJsonFileRelativePathSec: 'data-access/build-pipeline/config/dev-sec.json'