trigger:
 paths:
   include:
     - packages
 branches:
   include:
     - main

pr:
  branches:
    include:
      - main
  paths:
    include:
      - packages

pool:
  vmImage: ubuntu-latest

variables:
  deploymentDefaultLocation: 'eastus2'
  ServiceConnectionName: 'ShareThrift-MSDN'
  vmImageName: 'ubuntu-latest'
  system.debug: true
  npm_config_cache: $(Pipeline.Workspace)/.npm
  SONAR_USER_HOME: $(Pipeline.Workspace)/.sonar

stages:
  - template: ./packages/api/build-pipelines/azure-pipelines.yml
    parameters:
      vmImageName: $(vmImageName)
      ServiceConnectionName: $(ServiceConnectionName)
      npm_config_cache: $(npm_config_cache)
      SONAR_USER_HOME: $(SONAR_USER_HOME)
      deploymentDefaultLocation: $(deploymentDefaultLocation)
