packages:
  - "apps/*"
  - "packages/cellix/*"
  - "packages/sthrift/*"

catalog:
  mongoose: 8.17.0
  mongodb: 6.18.0
  # Vitest 4.x and related testing dependencies
  vitest: ^4.0.15
  '@vitest/coverage-v8': ^4.0.15
  '@vitest/browser-playwright': ^4.0.15
  storybook: 9.1.17

overrides:
  node-forge@<1.3.2: '>=1.3.2'