packages:
  - apps/*
  - packages/cellix/*
  - packages/sthrift/*

catalog:
  mongodb: 6.18.0
  mongoose: 8.17.0
  # Vitest 4.x and related testing dependencies
  vitest: ^4.0.15
  '@vitest/coverage-v8': ^4.0.15
  '@vitest/browser-playwright': ^4.0.15
  storybook: 9.1.17
  vite: ^7.3.0

overrides:
  '@azure/identity@<4.2.1': '>=4.2.1'
  axios@<0.30.0: '>=0.30.0'
  axios@<0.30.2: '>=0.30.2'
  axios@>=0.8.1 <0.28.0: '>=0.28.0'
  axios@>=1.0.0 <1.12.0: '>=1.12.0'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  glob@>=11.0.0 <11.1.0: '>=11.1.0'
  'gray-matter>js-yaml': '3.14.2'
  js-yaml@<3.14.2: '>=3.14.2'
  jws@<3.2.3: '>=3.2.3'
  jws@=4.0.0: '>=4.0.1'
  node-forge@<1.3.2: '>=1.3.2'
  qs@<6.14.1: '>=6.14.1'
  rollup@>=3.0.0 <3.29.5: '>=3.29.5'
  tough-cookie@<4.1.3: '>=4.1.3'
  validator@<13.15.22: '>=13.15.22'
  xml2js@<0.5.0: '>=0.5.0'
