import { describe, it, expect } from 'vitest';
import sidebars from './sidebars';

describe('Sidebars Config', () => {
  it('should have valid sidebar configuration', () => {
    // Test that sidebars is defined and has the expected structure
    expect(sidebars).toBeDefined();
    expect(typeof sidebars).toBe('object');
  });

  it('should have docsSidebar configuration', () => {
    // Test that docsSidebar exists and is configured
    expect(sidebars.docsSidebar).toBeDefined();
    expect(Array.isArray(sidebars.docsSidebar)).toBe(true);
  });

  it('should have autogenerated sidebar configuration', () => {
    // Test the autogenerated configuration
    const { docsSidebar } = sidebars;
    expect(docsSidebar).toHaveLength(1);
    expect(docsSidebar[0]).toEqual({
      type: 'autogenerated',
      dirName: '.',
    });
  });

  it('should have proper sidebar structure for documentation', () => {
    expect(Object.keys(sidebars)).toContain('docsSidebar');
    
    // Test that the configuration is using the correct type
    const { docsSidebar } = sidebars;
    expect(docsSidebar[0]).toHaveProperty('type', 'autogenerated');
    expect(docsSidebar[0]).toHaveProperty('dirName', '.');
  });
});
