query SharerInformationContainer($sharerId: ObjectID!) {
	userById(id: $sharerId) {
		...SharerPersonalUserFields
	}
}

fragment SharerPersonalUserFields on PersonalUser {
	id
	userType
	isBlocked
	account {
		...SharerPersonalUserAccountFields
	}
}

fragment SharerPersonalUserAccountFields on PersonalUserAccount {
	username
	profile {
		...SharerPersonalUserProfileFields
	}
}

fragment SharerPersonalUserProfileFields on PersonalUserAccountProfile {
	firstName
	lastName
	location {
		city
		state
		country
	}
}

mutation CreateConversation($input: ConversationCreateInput!) {
	createConversation(input: $input) {
		status {
			success
			errorMessage
		}
		conversation {
			id
			messagingConversationId
		}
	}
}
