import type { Models } from '@sthrift/data-sources-mongoose-models';
import { ObjectId } from 'mongodb';

export const personalUsers = [
	{
		_id: new ObjectId('507f1f77bcf86cd799439011'),
		userType: 'personal-users',
		isBlocked: false,
		hasCompletedOnboarding: true,
		account: {
			accountType: 'verified-personal',
			email: 'alice@example.com',
			username: 'alice',
			profile: {
				firstName: 'Alice',
				lastName: 'Smith',
				aboutMe: 'Hello',
				location: {
					address1: '123 Main St',
					address2: null,
					city: 'Springfield',
					state: 'IL',
					country: 'USA',
					zipCode: '62701',
				} as Models.User.PersonalUserAccountProfileLocation,
				billing: {
					subscriptionId: 'sub_001',
					cybersourceCustomerId: 'cyber_001',
					paymentState: 'SUCCEEDED',
					lastTransactionId: 'txn_001',
					lastPaymentAmount: 100,
				} as Models.User.PersonalUserAccountProfileBilling,
			} as Models.User.PersonalUserAccountProfile,
		} as Models.User.PersonalUserAccount,
		schemaVersion: '1.0.0',
		version: 1,
		discriminatorKey: 'personal-users',
		createdAt: new Date('2023-01-01T10:00:00Z'),
		updatedAt: new Date('2023-01-01T10:00:00Z'),
	},
	{
		_id: new ObjectId('507f1f77bcf86cd799439012'),
		userType: 'personal-users',
		isBlocked: false,
		hasCompletedOnboarding: true,
		account: {
			accountType: 'verified-personal',
			email: 'bob@example.com',
			username: 'bob',
			profile: {
				firstName: 'Bob',
				lastName: 'Johnson',
				aboutMe: 'Hello',
				location: {
					address1: '456 Oak Ave',
					address2: 'Apt 2',
					city: 'Springfield',
					state: 'IL',
					country: 'USA',
					zipCode: '62701',
				} as Models.User.PersonalUserAccountProfileLocation,
				billing: {
					subscriptionId: 'sub_002',
					cybersourceCustomerId: 'cyber_002',
					paymentState: 'PENDING',
					lastTransactionId: 'txn_002',
					lastPaymentAmount: 50,
				} as Models.User.PersonalUserAccountProfileBilling,
			} as Models.User.PersonalUserAccountProfile,
		} as Models.User.PersonalUserAccount,
		schemaVersion: '1.0.0',
		version: 1,
		discriminatorKey: 'personal-users',
		createdAt: new Date('2023-01-02T11:00:00Z'),
		updatedAt: new Date('2023-01-02T11:00:00Z'),
	},
	{
		_id: '507f1f77bcf86cd799439013',
		userType: 'personal-users',
		isBlocked: false,
		hasCompletedOnboarding: true,
		account: {
			accountType: 'verified-personal',
			email: 'nkduy2010@gmail.com', // from mock OAuth2 server
			username: 'duynguyen_personal',
			profile: {
				firstName: 'Duy',
				lastName: 'Nguyen',
				location: {
					address1: '789 Personal St',
					address2: null,
					city: 'Springfield',
					state: 'IL',
					country: 'USA',
					zipCode: '62701',
				} as Models.User.PersonalUserAccountProfileLocation,
				billing: {
					subscriptionId: 'sub_003',
					cybersourceCustomerId: 'cyber_003',
					paymentState: 'SUCCEEDED',
					lastTransactionId: 'txn_003',
					lastPaymentAmount: 75,
				} as Models.User.PersonalUserAccountProfileBilling,
			} as Models.User.PersonalUserAccountProfile,
		} as Models.User.PersonalUserAccount,
		schemaVersion: '1.0.0',
		version: 1,
		discriminatorKey: 'personal-users',
		createdAt: new Date('2023-01-04T10:00:00Z'),
		updatedAt: new Date('2023-01-04T10:00:00Z'),
	},
] as unknown as Models.User.PersonalUser[];
