import type { Country } from './../../../shared/payment/country-type.ts';

// Extracted US states
const US_STATES = [
	{ stateCode: 'AL', stateName: 'Alabama' },
	{ stateCode: 'AK', stateName: 'Alaska' },
	{ stateCode: 'AS', stateName: 'American Samoa' },
	{ stateCode: 'AZ', stateName: 'Arizona' },
	{ stateCode: 'AR', stateName: 'Arkansas' },
	{ stateCode: 'AA', stateName: 'Armed Forces Americas' },
	{ stateCode: 'AE', stateName: 'Armed Forces Europe' },
	{ stateCode: 'AP', stateName: 'Armed Forces Pacific' },
	{ stateCode: 'CA', stateName: 'California' },
	{ stateCode: 'CO', stateName: 'Colorado' },
	{ stateCode: 'CT', stateName: 'Connecticut' },
	{ stateCode: 'DE', stateName: 'Delaware' },
	{ stateCode: 'DC', stateName: 'District of Columbia' },
	{ stateCode: 'FM', stateName: 'Federated Micronesia' },
	{ stateCode: 'FL', stateName: 'Florida' },
	{ stateCode: 'GA', stateName: 'Georgia' },
	{ stateCode: 'GU', stateName: 'Guam' },
	{ stateCode: 'HI', stateName: 'Hawaii' },
	{ stateCode: 'ID', stateName: 'Idaho' },
	{ stateCode: 'IL', stateName: 'Illinois' },
	{ stateCode: 'IN', stateName: 'Indiana' },
	{ stateCode: 'IA', stateName: 'Iowa' },
	{ stateCode: 'KS', stateName: 'Kansas' },
	{ stateCode: 'KY', stateName: 'Kentucky' },
	{ stateCode: 'LA', stateName: 'Louisiana' },
	{ stateCode: 'ME', stateName: 'Maine' },
	{ stateCode: 'MH', stateName: 'Marshall Islands' },
	{ stateCode: 'MD', stateName: 'Maryland' },
	{ stateCode: 'MA', stateName: 'Massachusetts' },
	{ stateCode: 'MI', stateName: 'Michigan' },
	{ stateCode: 'MN', stateName: 'Minnesota' },
	{ stateCode: 'MS', stateName: 'Mississippi' },
	{ stateCode: 'MO', stateName: 'Missouri' },
	{ stateCode: 'MT', stateName: 'Montana' },
	{ stateCode: 'NE', stateName: 'Nebraska' },
	{ stateCode: 'NV', stateName: 'Nevada' },
	{ stateCode: 'NH', stateName: 'New Hampshire' },
	{ stateCode: 'NJ', stateName: 'New Jersey' },
	{ stateCode: 'NM', stateName: 'New Mexico' },
	{ stateCode: 'NY', stateName: 'New York' },
	{ stateCode: 'NC', stateName: 'North Carolina' },
	{ stateCode: 'ND', stateName: 'North Dakota' },
	{ stateCode: 'MP', stateName: 'Northern Mariana Islands' },
	{ stateCode: 'OH', stateName: 'Ohio' },
	{ stateCode: 'OK', stateName: 'Oklahoma' },
	{ stateCode: 'OR', stateName: 'Oregon' },
	{ stateCode: 'PW', stateName: 'Palau' },
	{ stateCode: 'PA', stateName: 'Pennsylvania' },
	{ stateCode: 'PR', stateName: 'Puerto Rico' },
	{ stateCode: 'RI', stateName: 'Rhode Island' },
	{ stateCode: 'SC', stateName: 'South Carolina' },
	{ stateCode: 'SD', stateName: 'South Dakota' },
	{ stateCode: 'TN', stateName: 'Tennessee' },
	{ stateCode: 'TX', stateName: 'Texas' },
	{ stateCode: 'UM', stateName: 'United States Minor Outlying Islands' },
	{ stateCode: 'VI', stateName: 'US Virgin Islands' },
	{ stateCode: 'UT', stateName: 'Utah' },
	{ stateCode: 'VT', stateName: 'Vermont' },
	{ stateCode: 'VA', stateName: 'Virginia' },
	{ stateCode: 'WA', stateName: 'Washington' },
	{ stateCode: 'WV', stateName: 'West Virginia' },
	{ stateCode: 'WI', stateName: 'Wisconsin' },
	{ stateCode: 'WY', stateName: 'Wyoming' },
];

// Extracted Canada provinces/territories
const CA_STATES = [
	{ stateCode: 'AB', stateName: 'Alberta' },
	{ stateCode: 'BC', stateName: 'British Columbia' },
	{ stateCode: 'MB', stateName: 'Manitoba' },
	{ stateCode: 'NB', stateName: 'New Brunswick' },
	{ stateCode: 'NL', stateName: 'Newfoundland and Labrador' },
	{ stateCode: 'NT', stateName: 'Northwest Territories' },
	{ stateCode: 'NS', stateName: 'Nova Scotia' },
	{ stateCode: 'NU', stateName: 'Nunavut' },
	{ stateCode: 'ON', stateName: 'Ontario' },
	{ stateCode: 'PE', stateName: 'Prince Edward Island' },
	{ stateCode: 'QC', stateName: 'Quebec' },
	{ stateCode: 'SK', stateName: 'Saskatchewan' },
	{ stateCode: 'YT', stateName: 'Yukon Territories' },
];

export const countriesMockData: Country[] = [
	{
		countryCode: 'AF',
		countryName: 'Afghanistan',
		states: null,
	},
	{
		countryCode: 'AX',
		countryName: 'Aland Islands',
		states: null,
	},
	{
		countryCode: 'AL',
		countryName: 'Albania',
		states: null,
	},
	{
		countryCode: 'DZ',
		countryName: 'Algeria',
		states: null,
	},
	{
		countryCode: 'AS',
		countryName: 'American Samoa',
		states: null,
	},
	{
		countryCode: 'AD',
		countryName: 'Andorra',
		states: null,
	},
	{
		countryCode: 'AO',
		countryName: 'Angola',
		states: null,
	},
	{
		countryCode: 'AI',
		countryName: 'Anguilla',
		states: null,
	},
	{
		countryCode: 'AQ',
		countryName: 'Antarctica',
		states: null,
	},
	{
		countryCode: 'AG',
		countryName: 'Antigua and Barbuda',
		states: null,
	},
	{
		countryCode: 'AR',
		countryName: 'Argentina',
		states: null,
	},
	{
		countryCode: 'AM',
		countryName: 'Armenia',
		states: null,
	},
	{
		countryCode: 'AW',
		countryName: 'Aruba',
		states: null,
	},
	{
		countryCode: 'AU',
		countryName: 'Australia',
		states: null,
	},
	{
		countryCode: 'AT',
		countryName: 'Austria',
		states: null,
	},
	{
		countryCode: 'AZ',
		countryName: 'Azerbaijan',
		states: null,
	},
	{
		countryCode: 'BS',
		countryName: 'Bahamas',
		states: null,
	},
	{
		countryCode: 'BH',
		countryName: 'Bahrain',
		states: null,
	},
	{
		countryCode: 'BD',
		countryName: 'Bangladesh',
		states: null,
	},
	{
		countryCode: 'BB',
		countryName: 'Barbados',
		states: null,
	},
	{
		countryCode: 'BY',
		countryName: 'Belarus',
		states: null,
	},
	{
		countryCode: 'BE',
		countryName: 'Belgium',
		states: null,
	},
	{
		countryCode: 'BZ',
		countryName: 'Belize',
		states: null,
	},
	{
		countryCode: 'BJ',
		countryName: 'Benin',
		states: null,
	},
	{
		countryCode: 'BM',
		countryName: 'Bermuda',
		states: null,
	},
	{
		countryCode: 'BT',
		countryName: 'Bhutan',
		states: null,
	},
	{
		countryCode: 'BO',
		countryName: 'Bolivia, Plurinational State of',
		states: null,
	},
	{
		countryCode: 'BQ',
		countryName: 'Bonaire, Sint Eustatius and Saba',
		states: null,
	},
	{
		countryCode: 'BA',
		countryName: 'Bosnia and Herzegovina',
		states: null,
	},
	{
		countryCode: 'BW',
		countryName: 'Botswana',
		states: null,
	},
	{
		countryCode: 'BV',
		countryName: 'Bouvet Island',
		states: null,
	},
	{
		countryCode: 'BR',
		countryName: 'Brazil',
		states: null,
	},
	{
		countryCode: 'IO',
		countryName: 'British Indian Ocean Territory',
		states: null,
	},
	{
		countryCode: 'BN',
		countryName: 'Brunei Darussalam',
		states: null,
	},
	{
		countryCode: 'BG',
		countryName: 'Bulgaria',
		states: null,
	},
	{
		countryCode: 'BF',
		countryName: 'Burkina Faso',
		states: null,
	},
	{
		countryCode: 'BI',
		countryName: 'Burundi',
		states: null,
	},
	{
		countryCode: 'KH',
		countryName: 'Cambodia',
		states: null,
	},
	{
		countryCode: 'CM',
		countryName: 'Cameroon',
		states: null,
	},
  {
    countryCode: 'CA',
    countryName: 'Canada',
    states: CA_STATES,
  },
	{
		countryCode: 'IC',
		countryName: 'Canary Islands',
		states: null,
	},
	{
		countryCode: 'CV',
		countryName: 'Cape Verde',
		states: null,
	},
	{
		countryCode: 'CF',
		countryName: 'Central African Republic',
		states: null,
	},
	{
		countryCode: 'TD',
		countryName: 'Chad',
		states: null,
	},
	{
		countryCode: 'CL',
		countryName: 'Chile',
		states: null,
	},
	{
		countryCode: 'CN',
		countryName: 'China',
		states: null,
	},
	{
		countryCode: 'CX',
		countryName: 'Christmas Island',
		states: null,
	},
	{
		countryCode: 'CC',
		countryName: 'Cocos (Keeling) Islands',
		states: null,
	},
	{
		countryCode: 'CO',
		countryName: 'Colombia',
		states: null,
	},
	{
		countryCode: 'KM',
		countryName: 'Comoros',
		states: null,
	},
	{
		countryCode: 'CG',
		countryName: 'Congo',
		states: null,
	},
	{
		countryCode: 'CD',
		countryName: 'Congo, the Democratic Republic of the',
		states: null,
	},
	{
		countryCode: 'CK',
		countryName: 'Cook Islands',
		states: null,
	},
	{
		countryCode: 'CR',
		countryName: 'Costa Rica',
		states: null,
	},
	{
		countryCode: 'CI',
		countryName: "Cote d'Ivoire",
		states: null,
	},
	{
		countryCode: 'HR',
		countryName: 'Croatia',
		states: null,
	},
	{
		countryCode: 'CU',
		countryName: 'Cuba',
		states: null,
	},
	{
		countryCode: 'CW',
		countryName: 'CuraÃ§ao',
		states: null,
	},
	{
		countryCode: 'CY',
		countryName: 'Cyprus',
		states: null,
	},
	{
		countryCode: 'CZ',
		countryName: 'Czech Republic',
		states: null,
	},
	{
		countryCode: 'DK',
		countryName: 'Denmark',
		states: null,
	},
	{
		countryCode: 'DJ',
		countryName: 'Djibouti',
		states: null,
	},
	{
		countryCode: 'DM',
		countryName: 'Dominica',
		states: null,
	},
	{
		countryCode: 'DO',
		countryName: 'Dominican Republic',
		states: null,
	},
	{
		countryCode: 'EC',
		countryName: 'Ecuador',
		states: null,
	},
	{
		countryCode: 'EG',
		countryName: 'Egypt',
		states: null,
	},
	{
		countryCode: 'SV',
		countryName: 'El Salvador',
		states: null,
	},
	{
		countryCode: 'GQ',
		countryName: 'Equatorial Guinea',
		states: null,
	},
	{
		countryCode: 'ER',
		countryName: 'Eritrea',
		states: null,
	},
	{
		countryCode: 'EE',
		countryName: 'Estonia',
		states: null,
	},
	{
		countryCode: 'EW',
		countryName: 'Eswatini',
		states: null,
	},
	{
		countryCode: 'ET',
		countryName: 'Ethiopia',
		states: null,
	},
	{
		countryCode: 'FK',
		countryName: 'Falkland Islands (Malvinas)',
		states: null,
	},
	{
		countryCode: 'FO',
		countryName: 'Faroe Islands',
		states: null,
	},
	{
		countryCode: 'FJ',
		countryName: 'Fiji',
		states: null,
	},
	{
		countryCode: 'FI',
		countryName: 'Finland',
		states: null,
	},
	{
		countryCode: 'FR',
		countryName: 'France',
		states: null,
	},
	{
		countryCode: 'GF',
		countryName: 'French Guiana',
		states: null,
	},
	{
		countryCode: 'PF',
		countryName: 'French Polynesia',
		states: null,
	},
	{
		countryCode: 'TF',
		countryName: 'French Southern Territories',
		states: null,
	},
	{
		countryCode: 'GA',
		countryName: 'Gabon',
		states: null,
	},
	{
		countryCode: 'GM',
		countryName: 'Gambia',
		states: null,
	},
	{
		countryCode: 'GE',
		countryName: 'Georgia',
		states: null,
	},
	{
		countryCode: 'DE',
		countryName: 'Germany',
		states: null,
	},
	{
		countryCode: 'GH',
		countryName: 'Ghana',
		states: null,
	},
	{
		countryCode: 'GI',
		countryName: 'Gibraltar',
		states: null,
	},
	{
		countryCode: 'GR',
		countryName: 'Greece',
		states: null,
	},
	{
		countryCode: 'GL',
		countryName: 'Greenland',
		states: null,
	},
	{
		countryCode: 'GD',
		countryName: 'Grenada',
		states: null,
	},
	{
		countryCode: 'GP',
		countryName: 'Guadeloupe',
		states: null,
	},
	{
		countryCode: 'GU',
		countryName: 'Guam',
		states: null,
	},
	{
		countryCode: 'GT',
		countryName: 'Guatemala',
		states: null,
	},
	{
		countryCode: 'GG',
		countryName: 'Guernsey',
		states: null,
	},
	{
		countryCode: 'GN',
		countryName: 'Guinea',
		states: null,
	},
	{
		countryCode: 'GW',
		countryName: 'Guinea-Bissau',
		states: null,
	},
	{
		countryCode: 'GY',
		countryName: 'Guyana',
		states: null,
	},
	{
		countryCode: 'HT',
		countryName: 'Haiti',
		states: null,
	},
	{
		countryCode: 'HM',
		countryName: 'Heard Island and McDonald Islands',
		states: null,
	},
	{
		countryCode: 'VA',
		countryName: 'Holy See (Vatican City State)',
		states: null,
	},
	{
		countryCode: 'HN',
		countryName: 'Honduras',
		states: null,
	},
	{
		countryCode: 'HK',
		countryName: 'Hong Kong',
		states: null,
	},
	{
		countryCode: 'HU',
		countryName: 'Hungary',
		states: null,
	},
	{
		countryCode: 'IS',
		countryName: 'Iceland',
		states: null,
	},
	{
		countryCode: 'IN',
		countryName: 'India',
		states: null,
	},
	{
		countryCode: 'ID',
		countryName: 'Indonesia',
		states: null,
	},
	{
		countryCode: 'IR',
		countryName: 'Iran, Islamic Republic of',
		states: null,
	},
	{
		countryCode: 'IQ',
		countryName: 'Iraq',
		states: null,
	},
	{
		countryCode: 'IE',
		countryName: 'Ireland',
		states: null,
	},
	{
		countryCode: 'IM',
		countryName: 'Isle of Man',
		states: null,
	},
	{
		countryCode: 'IL',
		countryName: 'Israel',
		states: null,
	},
	{
		countryCode: 'IT',
		countryName: 'Italy',
		states: null,
	},
	{
		countryCode: 'JM',
		countryName: 'Jamaica',
		states: null,
	},
	{
		countryCode: 'JP',
		countryName: 'Japan',
		states: null,
	},
	{
		countryCode: 'JE',
		countryName: 'Jersey',
		states: null,
	},
	{
		countryCode: 'JO',
		countryName: 'Jordan',
		states: null,
	},
	{
		countryCode: 'KZ',
		countryName: 'Kazakhstan',
		states: null,
	},
	{
		countryCode: 'KE',
		countryName: 'Kenya',
		states: null,
	},
	{
		countryCode: 'KI',
		countryName: 'Kiribati',
		states: null,
	},
	{
		countryCode: 'KP',
		countryName: "Korea, Democratic People's Republic of",
		states: null,
	},
	{
		countryCode: 'KR',
		countryName: 'Korea, Republic of',
		states: null,
	},
	{
		countryCode: 'KW',
		countryName: 'Kuwait',
		states: null,
	},
	{
		countryCode: 'KG',
		countryName: 'Kyrgyzstan',
		states: null,
	},
	{
		countryCode: 'LA',
		countryName: "Lao People's Democratic Republic",
		states: null,
	},
	{
		countryCode: 'LV',
		countryName: 'Latvia',
		states: null,
	},
	{
		countryCode: 'LB',
		countryName: 'Lebanon',
		states: null,
	},
	{
		countryCode: 'LS',
		countryName: 'Lesotho',
		states: null,
	},
	{
		countryCode: 'LR',
		countryName: 'Liberia',
		states: null,
	},
	{
		countryCode: 'LY',
		countryName: 'Libya',
		states: null,
	},
	{
		countryCode: 'LI',
		countryName: 'Liechtenstein',
		states: null,
	},
	{
		countryCode: 'LT',
		countryName: 'Lithuania',
		states: null,
	},
	{
		countryCode: 'LU',
		countryName: 'Luxembourg',
		states: null,
	},
	{
		countryCode: 'MO',
		countryName: 'Macao',
		states: null,
	},
	{
		countryCode: 'MK',
		countryName: 'Macedonia, the former Yugoslav Republic of',
		states: null,
	},
	{
		countryCode: 'MG',
		countryName: 'Madagascar',
		states: null,
	},
	{
		countryCode: 'MW',
		countryName: 'Malawi',
		states: null,
	},
	{
		countryCode: 'MY',
		countryName: 'Malaysia',
		states: null,
	},
	{
		countryCode: 'MV',
		countryName: 'Maldives',
		states: null,
	},
	{
		countryCode: 'ML',
		countryName: 'Mali',
		states: null,
	},
	{
		countryCode: 'MT',
		countryName: 'Malta',
		states: null,
	},
	{
		countryCode: 'MH',
		countryName: 'Marshall Islands',
		states: null,
	},
	{
		countryCode: 'MQ',
		countryName: 'Martinique',
		states: null,
	},
	{
		countryCode: 'MR',
		countryName: 'Mauritania',
		states: null,
	},
	{
		countryCode: 'MU',
		countryName: 'Mauritius',
		states: null,
	},
	{
		countryCode: 'YT',
		countryName: 'Mayotte',
		states: null,
	},
	{
		countryCode: 'MX',
		countryName: 'Mexico',
		states: null,
	},
	{
		countryCode: 'FM',
		countryName: 'Micronesia',
		states: null,
	},
	{
		countryCode: 'MD',
		countryName: 'Moldova, Republic of',
		states: null,
	},
	{
		countryCode: 'MC',
		countryName: 'Monaco',
		states: null,
	},
	{
		countryCode: 'MN',
		countryName: 'Mongolia',
		states: null,
	},
	{
		countryCode: 'ME',
		countryName: 'Montenegro',
		states: null,
	},
	{
		countryCode: 'MS',
		countryName: 'Montserrat',
		states: null,
	},
	{
		countryCode: 'MA',
		countryName: 'Morocco',
		states: null,
	},
	{
		countryCode: 'MZ',
		countryName: 'Mozambique',
		states: null,
	},
	{
		countryCode: 'MM',
		countryName: 'Myanmar',
		states: null,
	},
	{
		countryCode: 'NA',
		countryName: 'Namibia',
		states: null,
	},
	{
		countryCode: 'NR',
		countryName: 'Nauru',
		states: null,
	},
	{
		countryCode: 'NP',
		countryName: 'Nepal',
		states: null,
	},
	{
		countryCode: 'NL',
		countryName: 'Netherlands',
		states: null,
	},
	{
		countryCode: 'NC',
		countryName: 'New Caledonia',
		states: null,
	},
	{
		countryCode: 'NZ',
		countryName: 'New Zealand',
		states: null,
	},
	{
		countryCode: 'NI',
		countryName: 'Nicaragua',
		states: null,
	},
	{
		countryCode: 'NE',
		countryName: 'Niger',
		states: null,
	},
	{
		countryCode: 'NG',
		countryName: 'Nigeria',
		states: null,
	},
	{
		countryCode: 'NU',
		countryName: 'Niue',
		states: null,
	},
	{
		countryCode: 'NF',
		countryName: 'Norfolk Island',
		states: null,
	},
	{
		countryCode: 'MP',
		countryName: 'Northern Mariana Islands',
		states: null,
	},
	{
		countryCode: 'NO',
		countryName: 'Norway',
		states: null,
	},
	{
		countryCode: 'OM',
		countryName: 'Oman',
		states: null,
	},
	{
		countryCode: 'PK',
		countryName: 'Pakistan',
		states: null,
	},
	{
		countryCode: 'PW',
		countryName: 'Palau',
		states: null,
	},
	{
		countryCode: 'PS',
		countryName: 'Palestine',
		states: null,
	},
	{
		countryCode: 'PA',
		countryName: 'Panama',
		states: null,
	},
	{
		countryCode: 'PG',
		countryName: 'Papua New Guinea',
		states: null,
	},
	{
		countryCode: 'PY',
		countryName: 'Paraguay',
		states: null,
	},
	{
		countryCode: 'PE',
		countryName: 'Peru',
		states: null,
	},
	{
		countryCode: 'PH',
		countryName: 'Philippines',
		states: null,
	},
	{
		countryCode: 'PN',
		countryName: 'Pitcairn',
		states: null,
	},
	{
		countryCode: 'PL',
		countryName: 'Poland',
		states: null,
	},
	{
		countryCode: 'PT',
		countryName: 'Portugal',
		states: null,
	},
	{
		countryCode: 'PR',
		countryName: 'Puerto Rico',
		states: null,
	},
	{
		countryCode: 'QA',
		countryName: 'Qatar',
		states: null,
	},
	{
		countryCode: 'RE',
		countryName: 'Reunion',
		states: null,
	},
	{
		countryCode: 'RO',
		countryName: 'Romania',
		states: null,
	},
	{
		countryCode: 'RU',
		countryName: 'Russian Federation',
		states: null,
	},
	{
		countryCode: 'RW',
		countryName: 'Rwanda',
		states: null,
	},
	{
		countryCode: 'BL',
		countryName: 'Saint BarthÃ©lemy',
		states: null,
	},
	{
		countryCode: 'SH',
		countryName: 'Saint Helena, Ascension and Tristan da Cunha',
		states: null,
	},
	{
		countryCode: 'KN',
		countryName: 'Saint Kitts and Nevis',
		states: null,
	},
	{
		countryCode: 'LC',
		countryName: 'Saint Lucia',
		states: null,
	},
	{
		countryCode: 'MF',
		countryName: 'Saint Martin (French part)',
		states: null,
	},
	{
		countryCode: 'PM',
		countryName: 'Saint Pierre and Miquelon',
		states: null,
	},
	{
		countryCode: 'VC',
		countryName: 'Saint Vincent and the Grenadines',
		states: null,
	},
	{
		countryCode: 'WS',
		countryName: 'Samoa',
		states: null,
	},
	{
		countryCode: 'SM',
		countryName: 'San Marino',
		states: null,
	},
	{
		countryCode: 'ST',
		countryName: 'Sao Tome and Principe',
		states: null,
	},
	{
		countryCode: 'SA',
		countryName: 'Saudi Arabia',
		states: null,
	},
	{
		countryCode: 'SN',
		countryName: 'Senegal',
		states: null,
	},
	{
		countryCode: 'RS',
		countryName: 'Serbia',
		states: null,
	},
	{
		countryCode: 'SC',
		countryName: 'Seychelles',
		states: null,
	},
	{
		countryCode: 'SL',
		countryName: 'Sierra Leone',
		states: null,
	},
	{
		countryCode: 'SG',
		countryName: 'Singapore',
		states: null,
	},
	{
		countryCode: 'SX',
		countryName: 'Sint Maarten (Dutch part)',
		states: null,
	},
	{
		countryCode: 'SK',
		countryName: 'Slovakia',
		states: null,
	},
	{
		countryCode: 'SI',
		countryName: 'Slovenia',
		states: null,
	},
	{
		countryCode: 'SB',
		countryName: 'Solomon Islands',
		states: null,
	},
	{
		countryCode: 'SO',
		countryName: 'Somalia',
		states: null,
	},
	{
		countryCode: 'ZA',
		countryName: 'South Africa',
		states: null,
	},
	{
		countryCode: 'GS',
		countryName: 'South Georgia and the South Sandwich Islands',
		states: null,
	},
	{
		countryCode: 'SS',
		countryName: 'South Sudan',
		states: null,
	},
	{
		countryCode: 'ES',
		countryName: 'Spain',
		states: null,
	},
	{
		countryCode: 'LK',
		countryName: 'Sri Lanka',
		states: null,
	},
	{
		countryCode: 'SD',
		countryName: 'Sudan',
		states: null,
	},
	{
		countryCode: 'SR',
		countryName: 'Suriname',
		states: null,
	},
	{
		countryCode: 'SJ',
		countryName: 'Svalbard and Jan Mayen',
		states: null,
	},
	{
		countryCode: 'SE',
		countryName: 'Sweden',
		states: null,
	},
	{
		countryCode: 'CH',
		countryName: 'Switzerland',
		states: null,
	},
	{
		countryCode: 'SY',
		countryName: 'Syrian Arab Republic',
		states: null,
	},
	{
		countryCode: 'TW',
		countryName: 'Taiwan',
		states: null,
	},
	{
		countryCode: 'TJ',
		countryName: 'Tajikistan',
		states: null,
	},
	{
		countryCode: 'TZ',
		countryName: 'Tanzania, United Republic of',
		states: null,
	},
	{
		countryCode: 'TH',
		countryName: 'Thailand',
		states: null,
	},
	{
		countryCode: 'TL',
		countryName: 'Timor-Leste',
		states: null,
	},
	{
		countryCode: 'TG',
		countryName: 'Togo',
		states: null,
	},
	{
		countryCode: 'TK',
		countryName: 'Tokelau',
		states: null,
	},
	{
		countryCode: 'TO',
		countryName: 'Tonga',
		states: null,
	},
	{
		countryCode: 'TT',
		countryName: 'Trinidad and Tobago',
		states: null,
	},
	{
		countryCode: 'TN',
		countryName: 'Tunisia',
		states: null,
	},
	{
		countryCode: 'TR',
		countryName: 'Turkey',
		states: null,
	},
	{
		countryCode: 'TM',
		countryName: 'Turkmenistan',
		states: null,
	},
	{
		countryCode: 'TC',
		countryName: 'Turks and Caicos Islands',
		states: null,
	},
	{
		countryCode: 'TV',
		countryName: 'Tuvalu',
		states: null,
	},
	{
		countryCode: 'UG',
		countryName: 'Uganda',
		states: null,
	},
	{
		countryCode: 'UA',
		countryName: 'Ukraine',
		states: null,
	},
	{
		countryCode: 'AE',
		countryName: 'United Arab Emirates',
		states: null,
	},
	{
		countryCode: 'GB',
		countryName: 'United Kingdom',
		states: null,
	},
  {
    countryCode: 'US',
    countryName: 'United States',
    states: US_STATES,
  },
	{
		countryCode: 'UM',
		countryName: 'United States Minor Outlying Islands (the)',
		states: null,
	},
	{
		countryCode: 'UY',
		countryName: 'Uruguay',
		states: null,
	},
	{
		countryCode: 'UZ',
		countryName: 'Uzbekistan',
		states: null,
	},
	{
		countryCode: 'VU',
		countryName: 'Vanuatu',
		states: null,
	},
	{
		countryCode: 'VE',
		countryName: 'Venezuela, Bolivarian Republic of',
		states: null,
	},
	{
		countryCode: 'VN',
		countryName: 'Vietnam',
		states: null,
	},
	{
		countryCode: 'VG',
		countryName: 'Virgin Islands, British',
		states: null,
	},
	{
		countryCode: 'VI',
		countryName: 'Virgin Islands (U.S.)',
		states: null,
	},
	{
		countryCode: 'WF',
		countryName: 'Wallis and Futuna',
		states: null,
	},
	{
		countryCode: 'WB',
		countryName: 'West Bank',
		states: null,
	},
	{
		countryCode: 'EH',
		countryName: 'Western Sahara',
		states: null,
	},
	{
		countryCode: 'YE',
		countryName: 'Yemen',
		states: null,
	},
	{
		countryCode: 'ZM',
		countryName: 'Zambia',
		states: null,
	},
	{
		countryCode: 'ZW',
		countryName: 'Zimbabwe',
		states: null,
	},
];
