query HomeAccountProfileViewContainerCurrentUser {
	currentUser {
		... on PersonalUser {
			id
			userType
			createdAt
			account {
				...PersonalUserProfileViewAccountFields
			}
		}
	}
}

query HomeAccountProfileViewContainerUserListings(
	$page: Int!
	$pageSize: Int!
) {
	myListingsAll(page: $page, pageSize: $pageSize) {
		items {
			id
			title
			state
			images
			createdAt
			sharingPeriodStart
			sharingPeriodEnd
		}
		total
		page
		pageSize
	}
}

fragment PersonalUserProfileViewAccountFields on PersonalUserAccount {
	accountType
	email
	username
	profile {
		...PersonalUserProfileViewAccountProfileFields
	}
}

fragment PersonalUserProfileViewAccountProfileFields on PersonalUserAccountProfile {
	firstName
	lastName
	location {
		city
		state
	}
}
