import type { Domain } from '@sthrift/domain';

export const getMockPersonalUsers = (): Domain.Contexts.User.PersonalUser.PersonalUserEntityReference[] => {
	// Mock users for development - returns 8 users with variety
	return [
		{
			id: '507f1f77bcf86cd799439011',
			userType: 'verified-personal',
			isBlocked: false,
			hasCompletedOnboarding: true,
			account: {
				accountType: 'verified-personal',
				email: 'alice.smith@example.com',
				username: 'alicesmith',
				profile: {
					firstName: 'Alice',
					lastName: 'Smith',
					location: {
						address1: '123 Main St',
						address2: null,
						city: 'Springfield',
						state: 'IL',
						country: 'USA',
						zipCode: '62701',
					},
					billing: {
						subscriptionId: 'sub_001',
						cybersourceCustomerId: 'cyber_001',
						paymentState: 'SUCCEEDED',
						lastTransactionId: 'txn_001',
						lastPaymentAmount: 100,
					},
				},
			},
			createdAt: new Date('2023-01-15T10:00:00Z'),
			updatedAt: new Date('2023-01-15T10:00:00Z'),
		} as Domain.Contexts.User.PersonalUser.PersonalUserEntityReference,
		{
			id: '507f1f77bcf86cd799439012',
			userType: 'verified-personal',
			isBlocked: true,
			hasCompletedOnboarding: true,
			account: {
				accountType: 'verified-personal',
				email: 'bob.johnson@example.com',
				username: 'bobjohnson',
				profile: {
					firstName: 'Bob',
					lastName: 'Johnson',
					location: {
						address1: '456 Oak Ave',
						address2: 'Apt 2',
						city: 'Chicago',
						state: 'IL',
						country: 'USA',
						zipCode: '60601',
					},
					billing: {
						subscriptionId: 'sub_002',
						cybersourceCustomerId: 'cyber_002',
						paymentState: 'PENDING',
						lastTransactionId: 'txn_002',
						lastPaymentAmount: 50,
					},
				},
			},
			createdAt: new Date('2023-02-20T11:00:00Z'),
			updatedAt: new Date('2023-02-20T11:00:00Z'),
		} as Domain.Contexts.User.PersonalUser.PersonalUserEntityReference,
		{
			id: '507f1f77bcf86cd799439014',
			userType: 'verified-personal-plus',
			isBlocked: false,
			hasCompletedOnboarding: true,
			account: {
				accountType: 'verified-personal-plus',
				email: 'diana.prince@example.com',
				username: 'dianaprince',
				profile: {
					firstName: 'Diana',
					lastName: 'Prince',
					location: {
						address1: '101 Wonder Ln',
						address2: null,
						city: 'Seattle',
						state: 'WA',
						country: 'USA',
						zipCode: '98101',
					},
					billing: {
						subscriptionId: 'sub_004',
						cybersourceCustomerId: 'cyber_004',
						paymentState: 'SUCCEEDED',
						lastTransactionId: 'txn_004',
						lastPaymentAmount: 150,
					},
				},
			},
			createdAt: new Date('2023-04-05T14:00:00Z'),
			updatedAt: new Date('2023-04-05T14:00:00Z'),
		} as Domain.Contexts.User.PersonalUser.PersonalUserEntityReference,
		{
			id: '507f1f77bcf86cd799439015',
			userType: 'verified-personal',
			isBlocked: true,
			hasCompletedOnboarding: true,
			account: {
				accountType: 'verified-personal',
				email: 'eve.wilson@example.com',
				username: 'evewilson',
				profile: {
					firstName: 'Eve',
					lastName: 'Wilson',
					location: {
						address1: '202 Elm St',
						address2: 'Suite 5',
						city: 'Portland',
						state: 'OR',
						country: 'USA',
						zipCode: '97201',
					},
					billing: {
						subscriptionId: 'sub_005',
						cybersourceCustomerId: 'cyber_005',
						paymentState: 'FAILED',
						lastTransactionId: 'txn_005',
						lastPaymentAmount: 75,
					},
				},
			},
			createdAt: new Date('2023-05-12T16:00:00Z'),
			updatedAt: new Date('2023-05-12T16:00:00Z'),
		} as Domain.Contexts.User.PersonalUser.PersonalUserEntityReference,
		{
			id: '507f1f77bcf86cd799439016',
			userType: 'verified-personal',
			isBlocked: false,
			hasCompletedOnboarding: true,
			account: {
				accountType: 'verified-personal',
				email: 'frank.miller@example.com',
				username: 'frankmiller',
				profile: {
					firstName: 'Frank',
					lastName: 'Miller',
					location: {
						address1: '303 Maple Dr',
						address2: null,
						city: 'Denver',
						state: 'CO',
						country: 'USA',
						zipCode: '80201',
					},
					billing: {
						subscriptionId: 'sub_006',
						cybersourceCustomerId: 'cyber_006',
						paymentState: 'SUCCEEDED',
						lastTransactionId: 'txn_006',
						lastPaymentAmount: 120,
					},
				},
			},
			createdAt: new Date('2023-06-18T10:00:00Z'),
			updatedAt: new Date('2023-06-18T10:00:00Z'),
		} as Domain.Contexts.User.PersonalUser.PersonalUserEntityReference,
		{
			id: '507f1f77bcf86cd799439018',
			userType: 'verified-personal',
			isBlocked: false,
			hasCompletedOnboarding: true,
			account: {
				accountType: 'verified-personal',
				email: 'henry.ford@example.com',
				username: 'henryford',
				profile: {
					firstName: 'Henry',
					lastName: 'Ford',
					location: {
						address1: '505 Auto Ave',
						address2: null,
						city: 'Detroit',
						state: 'MI',
						country: 'USA',
						zipCode: '48201',
					},
					billing: {
						subscriptionId: 'sub_008',
						cybersourceCustomerId: 'cyber_008',
						paymentState: 'SUCCEEDED',
						lastTransactionId: 'txn_008',
						lastPaymentAmount: 90,
					},
				},
			},
			createdAt: new Date('2023-08-30T08:00:00Z'),
			updatedAt: new Date('2023-08-30T08:00:00Z'),
		} as Domain.Contexts.User.PersonalUser.PersonalUserEntityReference,
		{
			id: '507f1f77bcf86cd799439019',
			userType: 'verified-personal-plus',
			isBlocked: false,
			hasCompletedOnboarding: true,
			account: {
				accountType: 'verified-personal-plus',
				email: 'iris.west@example.com',
				username: 'iriswest',
				profile: {
					firstName: 'Iris',
					lastName: 'West',
					location: {
						address1: '606 Speed St',
						address2: 'Floor 3',
						city: 'Central City',
						state: 'MO',
						country: 'USA',
						zipCode: '64101',
					},
					billing: {
						subscriptionId: 'sub_009',
						cybersourceCustomerId: 'cyber_009',
						paymentState: 'SUCCEEDED',
						lastTransactionId: 'txn_009',
						lastPaymentAmount: 200,
					},
				},
			},
			createdAt: new Date('2023-09-14T15:00:00Z'),
			updatedAt: new Date('2023-09-14T15:00:00Z'),
		} as Domain.Contexts.User.PersonalUser.PersonalUserEntityReference,
		{
			id: '507f1f77bcf86cd799439020',
			userType: 'verified-personal',
			isBlocked: true,
			hasCompletedOnboarding: true,
			account: {
				accountType: 'verified-personal',
				email: 'jack.sparrow@example.com',
				username: 'jacksparrow',
				profile: {
					firstName: 'Jack',
					lastName: 'Sparrow',
					location: {
						address1: '707 Pirate Cove',
						address2: null,
						city: 'Miami',
						state: 'FL',
						country: 'USA',
						zipCode: '33101',
					},
					billing: {
						subscriptionId: 'sub_010',
						cybersourceCustomerId: 'cyber_010',
						paymentState: 'FAILED',
						lastTransactionId: 'txn_010',
						lastPaymentAmount: 60,
					},
				},
			},
			createdAt: new Date('2023-10-01T17:00:00Z'),
			updatedAt: new Date('2023-10-01T17:00:00Z'),
		} as Domain.Contexts.User.PersonalUser.PersonalUserEntityReference,
	];
};
