parameters:
- name: environmentNameDevOps
  type: string
- name: vmImageName
  type: string

jobs:
- deployment: Deploy_UI_Sharethrift
  displayName: 'Deploy UI Sharethrift (Static Web App)'
  condition: eq(stageDependencies.Build.BuildJob.outputs['BuildJob.HAS_FRONTEND_CHANGES'], 'true')
  environment: ${{parameters.environmentNameDevOps}}
  pool:
    vmImage: ${{parameters.vmImageName}}
  strategy:
    runOnce:
      deploy:
        steps:
        - task: AzureStaticWebApp@0
          displayName: 'Azure Static Web App Deploy: Sharethrift-ui-sharethrift'
          inputs:
            azure_static_web_apps_api_token: $(deployment-token)
            action: 'Upload'
            app_location: 'apps/ui-sharethrift'
            api_location: ''
            output_location: 'dist'
            skip_app_build: false
            build_timeout_in_minutes: 15
