parameters:
- name: stageName
  displayName: 'Name of the Stage'
  type: string
- name: environmentNameBicep
  displayName: 'Environment Name in Bicep config- dev/qa/uat/prd'
  type: string
- name: environmentNameDevOps
  displayName: 'Environment Name in DevOps- Dev/QA/UAT/Production'
  type: string
- name: vmImageName
  displayName: 'VM Image - ubuntu-latest'
  type: string
- name: ServiceConnectionName
  displayName: 'Service Connection Name'
  type: string
- name: deploymentDefaultLocation
  displayName: 'Default Location for Deployment'
  type: string
- name: resourceGroupName
  displayName: 'Resource Group Name'
  type: string
- name: functionAppNamePri
  displayName: 'Function App Name for Primary instance'
  type: string

stages:
- stage: ${{parameters.stageName}}
  displayName: ${{parameters.stageName}} stage
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - template: ../../apps/api/deploy-api.yml
    parameters:
      ServiceConnectionName: ${{parameters.ServiceConnectionName}}
      deploymentDefaultLocation: ${{parameters.deploymentDefaultLocation}}
      resourceGroupName: ${{parameters.resourceGroupName}}
      environmentNameBicep: ${{parameters.environmentNameBicep}}
      environmentNameDevOps: ${{parameters.environmentNameDevOps}}
      vmImageName: ${{parameters.vmImageName}}
      functionAppNamePri: ${{parameters.functionAppNamePri}}
  - template: ../../apps/docs/deploy-docs.yml
    parameters:
      vmImageName: ${{parameters.vmImageName}}
  - template: ../../apps/ui-community/deploy-ui-community.yml
    parameters:
      environmentNameDevOps: ${{parameters.environmentNameDevOps}}
      vmImageName: ${{parameters.vmImageName}}
