parameters:
- name: stageName
  displayName: 'Name of the Stage'
  type: string
- name: environmentNameBicep
  displayName: 'Environment Name in Bicep config- dev/qa/uat/prd'
  type: string
- name: environmentNameDevOps
  displayName: 'Environment Name in DevOps- Dev/QA/UAT/Production'
  type: string
- name: vmImageName
  displayName: 'VM Image - ubuntu-latest'
  type: string
- name: ServiceConnectionName
  displayName: 'Service Connection Name'
  type: string
- name: deploymentDefaultLocation
  displayName: 'Default Location for Deployment'
  type: string
- name: resourceGroupName
  displayName: 'Resource Group Name'
  type: string
- name: appSettingsJsonFileRelativePathPri
  displayName: 'AppSettings Json File Relative Path for Primary instance'
  type: string
- name: frontDoorProfileName
  displayName: 'Front Door Profile Name'
  type: string
- name: frontDoorEndpointName
  displayName: 'Front Door Endpoint Name'
  type: string
stages:
- stage: ${{parameters.stageName}}
  displayName: ${{parameters.stageName}} stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - template: ../../apps/api/deploy-api.yml
    parameters:
      ServiceConnectionName: ${{parameters.ServiceConnectionName}}
      deploymentDefaultLocation: ${{parameters.deploymentDefaultLocation}}
      resourceGroupName: ${{parameters.resourceGroupName}}
      environmentNameBicep: ${{parameters.environmentNameBicep}}
      environmentNameDevOps: ${{parameters.environmentNameDevOps}}
      vmImageName: ${{parameters.vmImageName}}
      appSettingsJsonFileRelativePathPri: ${{parameters.appSettingsJsonFileRelativePathPri}}
  - template: ../../apps/docs/deploy-docs.yml
    parameters:
      vmImageName: ${{parameters.vmImageName}}
  - template: ../../apps/ui-sharethrift/deploy-ui-sharethrift.yml
    parameters:
      environmentNameDevOps: ${{parameters.environmentNameDevOps}}
      environmentNameBicep: ${{parameters.environmentNameBicep}}
      vmImageName: ${{parameters.vmImageName}}
      ServiceConnectionName: ${{parameters.ServiceConnectionName}}
      deploymentDefaultLocation: ${{parameters.deploymentDefaultLocation}}
      resourceGroupName: ${{parameters.resourceGroupName}}
      frontDoorProfileName: ${{parameters.frontDoorProfileName}}
      frontDoorEndpointName: ${{parameters.frontDoorEndpointName}}